//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public User()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int User_ID { get; set; }
        [Required(ErrorMessage = "you must enter your name!")]
        public string Name { get; set; }
        [Required(ErrorMessage = "you must enter your city!")]
        public string City { get; set; }

        [Required(ErrorMessage = "you must enter your Adress!")]
        public string Address { get; set; }
        [Required(ErrorMessage = "you must enter your Email!")]
        public string Email { get; set; }
        [Required(ErrorMessage = "you must enter your Password!")]
        public string Password { get; set; }
        [Required(ErrorMessage = "you must enter your Contact_number!")]
        [RegularExpression(@"^(\d{11})$", ErrorMessage = " follow this pattern :123456789")]
        public string Contact_Number { get; set; }
        public string Email_Verified { get; set; }

        [Required(ErrorMessage = "you must enter confirmed password!")]
        [Compare("Password", ErrorMessage = "both password must match")]
        public string Confirm_password { get; set; }
        public Nullable<System.DateTime> Registration_Date { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
